//! Note-name spellings per language, generated from LilyPond's
//! `scm/define-note-names.scm` by `tools/gen_note_names.py`. Do not edit by
//! hand; re-run the generator against a LilyPond checkout instead.
//!
//! Each table maps a spelling to its diatonic note name (`0 = c` … `6 = b`)
//! and alteration in quarter-tone steps (sharp `+2`, flat `-2`).

/// A note-name language selectable with `\language` or by including the
/// matching `.ly` file. [`Language::Nederlands`] is LilyPond's default.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Language {
    Catalan,
    Deutsch,
    English,
    Espanol,
    Francais,
    Italiano,
    Nederlands,
    Norsk,
    Portugues,
    SemiGerman,
    Suomi,
    Svenska,
    Vlaams,
}

impl Language {
    /// LilyPond's default note-name language, in force until a
    /// `\language` or language include changes it.
    pub const DEFAULT: Language = Language::Nederlands;

    /// The language a `\language "name"` string or a `name`(`.ly`) include
    /// selects, or `None` if it names no known language.
    pub fn from_name(name: &str) -> Option<Language> {
        Some(match name {
            "catalan" => Language::Catalan,
            "català" => Language::Catalan,
            "deutsch" => Language::Deutsch,
            "english" => Language::English,
            "espanol" => Language::Espanol,
            "español" => Language::Espanol,
            "francais" => Language::Francais,
            "français" => Language::Francais,
            "italiano" => Language::Italiano,
            "nederlands" => Language::Nederlands,
            "norsk" => Language::Norsk,
            "portugues" => Language::Portugues,
            "português" => Language::Portugues,
            "semi-german" => Language::SemiGerman,
            "suomi" => Language::Suomi,
            "svenska" => Language::Svenska,
            "vlaams" => Language::Vlaams,
            _ => return None,
        })
    }

    /// The note-name table for this language, sorted by spelling.
    fn table(self) -> &'static [(&'static str, u8, i8)] {
        match self {
            Language::Catalan => CATALAN_NAMES,
            Language::Deutsch => DEUTSCH_NAMES,
            Language::English => ENGLISH_NAMES,
            Language::Espanol => ESPANOL_NAMES,
            Language::Francais => FRANCAIS_NAMES,
            Language::Italiano => ITALIANO_NAMES,
            Language::Nederlands => NEDERLANDS_NAMES,
            Language::Norsk => NORSK_NAMES,
            Language::Portugues => PORTUGUES_NAMES,
            Language::SemiGerman => SEMI_GERMAN_NAMES,
            Language::Suomi => SUOMI_NAMES,
            Language::Svenska => SVENSKA_NAMES,
            Language::Vlaams => VLAAMS_NAMES,
        }
    }

    /// Resolves a note-name spelling to its `(note name, alteration)`, or
    /// `None` if this language has no such note.
    pub fn note(self, spelling: &str) -> Option<(u8, i8)> {
        self.table()
            .binary_search_by_key(&spelling, |&(name, _, _)| name)
            .ok()
            .map(|i| {
                let (_, note, alt) = self.table()[i];
                (note, alt)
            })
    }

    /// A spelling for the pitch `(note name, alteration)` in this language, or
    /// `None` if it has no name for it. Where a language gives several spellings
    /// (English `ef` and `e-flat`), the shortest is chosen, so callers get the
    /// terse form a writer would use rather than the spelled-out alias.
    pub fn spell(self, note_name: u8, alteration: i8) -> Option<&'static str> {
        self.table()
            .iter()
            .filter(|&&(_, note, alt)| note == note_name && alt == alteration)
            .map(|&(name, _, _)| name)
            .min_by_key(|name| name.len())
    }
}

#[rustfmt::skip]
static CATALAN_NAMES: &[(&str, u8, i8)] = &[
    ("do", 0, 0),
    ("dob", 0, -2),
    ("dobb", 0, -4),
    ("dod", 0, 2),
    ("dodd", 0, 4),
    ("doqb", 0, -1),
    ("doqd", 0, 1),
    ("doqs", 0, 1),
    ("dos", 0, 2),
    ("doss", 0, 4),
    ("dotqb", 0, -3),
    ("dotqd", 0, 3),
    ("dotqs", 0, 3),
    ("fa", 3, 0),
    ("fab", 3, -2),
    ("fabb", 3, -4),
    ("fad", 3, 2),
    ("fadd", 3, 4),
    ("faqb", 3, -1),
    ("faqd", 3, 1),
    ("faqs", 3, 1),
    ("fas", 3, 2),
    ("fass", 3, 4),
    ("fatqb", 3, -3),
    ("fatqd", 3, 3),
    ("fatqs", 3, 3),
    ("la", 5, 0),
    ("lab", 5, -2),
    ("labb", 5, -4),
    ("lad", 5, 2),
    ("ladd", 5, 4),
    ("laqb", 5, -1),
    ("laqd", 5, 1),
    ("laqs", 5, 1),
    ("las", 5, 2),
    ("lass", 5, 4),
    ("latqb", 5, -3),
    ("latqd", 5, 3),
    ("latqs", 5, 3),
    ("mi", 2, 0),
    ("mib", 2, -2),
    ("mibb", 2, -4),
    ("mid", 2, 2),
    ("midd", 2, 4),
    ("miqb", 2, -1),
    ("miqd", 2, 1),
    ("miqs", 2, 1),
    ("mis", 2, 2),
    ("miss", 2, 4),
    ("mitqb", 2, -3),
    ("mitqd", 2, 3),
    ("mitqs", 2, 3),
    ("re", 1, 0),
    ("reb", 1, -2),
    ("rebb", 1, -4),
    ("red", 1, 2),
    ("redd", 1, 4),
    ("reqb", 1, -1),
    ("reqd", 1, 1),
    ("reqs", 1, 1),
    ("res", 1, 2),
    ("ress", 1, 4),
    ("retqb", 1, -3),
    ("retqd", 1, 3),
    ("retqs", 1, 3),
    ("si", 6, 0),
    ("sib", 6, -2),
    ("sibb", 6, -4),
    ("sid", 6, 2),
    ("sidd", 6, 4),
    ("siqb", 6, -1),
    ("siqd", 6, 1),
    ("siqs", 6, 1),
    ("sis", 6, 2),
    ("siss", 6, 4),
    ("sitqb", 6, -3),
    ("sitqd", 6, 3),
    ("sitqs", 6, 3),
    ("sol", 4, 0),
    ("solb", 4, -2),
    ("solbb", 4, -4),
    ("sold", 4, 2),
    ("soldd", 4, 4),
    ("solqb", 4, -1),
    ("solqd", 4, 1),
    ("solqs", 4, 1),
    ("sols", 4, 2),
    ("solss", 4, 4),
    ("soltqb", 4, -3),
    ("soltqd", 4, 3),
    ("soltqs", 4, 3),
];

#[rustfmt::skip]
static DEUTSCH_NAMES: &[(&str, u8, i8)] = &[
    ("a", 5, 0),
    ("aeh", 5, -1),
    ("ah", 5, -1),
    ("aih", 5, 1),
    ("ais", 5, 2),
    ("aisih", 5, 3),
    ("aisis", 5, 4),
    ("as", 5, -2),
    ("asah", 5, -3),
    ("asas", 5, -4),
    ("aseh", 5, -3),
    ("ases", 5, -4),
    ("b", 6, -2),
    ("c", 0, 0),
    ("ceh", 0, -1),
    ("ces", 0, -2),
    ("ceseh", 0, -3),
    ("ceses", 0, -4),
    ("cih", 0, 1),
    ("cis", 0, 2),
    ("cisih", 0, 3),
    ("cisis", 0, 4),
    ("d", 1, 0),
    ("deh", 1, -1),
    ("des", 1, -2),
    ("deseh", 1, -3),
    ("deses", 1, -4),
    ("dih", 1, 1),
    ("dis", 1, 2),
    ("disih", 1, 3),
    ("disis", 1, 4),
    ("e", 2, 0),
    ("eeh", 2, -1),
    ("eh", 2, -1),
    ("eih", 2, 1),
    ("eis", 2, 2),
    ("eisih", 2, 3),
    ("eisis", 2, 4),
    ("es", 2, -2),
    ("eseh", 2, -3),
    ("eses", 2, -4),
    ("f", 3, 0),
    ("feh", 3, -1),
    ("fes", 3, -2),
    ("feseh", 3, -3),
    ("feses", 3, -4),
    ("fih", 3, 1),
    ("fis", 3, 2),
    ("fisih", 3, 3),
    ("fisis", 3, 4),
    ("g", 4, 0),
    ("geh", 4, -1),
    ("ges", 4, -2),
    ("geseh", 4, -3),
    ("geses", 4, -4),
    ("gih", 4, 1),
    ("gis", 4, 2),
    ("gisih", 4, 3),
    ("gisis", 4, 4),
    ("h", 6, 0),
    ("heh", 6, -1),
    ("heseh", 6, -3),
    ("heses", 6, -4),
    ("hih", 6, 1),
    ("his", 6, 2),
    ("hisih", 6, 3),
    ("hisis", 6, 4),
];

#[rustfmt::skip]
static ENGLISH_NAMES: &[(&str, u8, i8)] = &[
    ("a", 5, 0),
    ("a-flat", 5, -2),
    ("a-flatflat", 5, -4),
    ("a-natural", 5, 0),
    ("a-sharp", 5, 2),
    ("a-sharpsharp", 5, 4),
    ("af", 5, -2),
    ("aff", 5, -4),
    ("aqf", 5, -1),
    ("aqs", 5, 1),
    ("as", 5, 2),
    ("ass", 5, 4),
    ("atqf", 5, -3),
    ("atqs", 5, 3),
    ("ax", 5, 4),
    ("b", 6, 0),
    ("b-flat", 6, -2),
    ("b-flatflat", 6, -4),
    ("b-natural", 6, 0),
    ("b-sharp", 6, 2),
    ("b-sharpsharp", 6, 4),
    ("bf", 6, -2),
    ("bff", 6, -4),
    ("bqf", 6, -1),
    ("bqs", 6, 1),
    ("bs", 6, 2),
    ("bss", 6, 4),
    ("btqf", 6, -3),
    ("btqs", 6, 3),
    ("bx", 6, 4),
    ("c", 0, 0),
    ("c-flat", 0, -2),
    ("c-flatflat", 0, -4),
    ("c-natural", 0, 0),
    ("c-sharp", 0, 2),
    ("c-sharpsharp", 0, 4),
    ("cf", 0, -2),
    ("cff", 0, -4),
    ("cqf", 0, -1),
    ("cqs", 0, 1),
    ("cs", 0, 2),
    ("css", 0, 4),
    ("ctqf", 0, -3),
    ("ctqs", 0, 3),
    ("cx", 0, 4),
    ("d", 1, 0),
    ("d-flat", 1, -2),
    ("d-flatflat", 1, -4),
    ("d-natural", 1, 0),
    ("d-sharp", 1, 2),
    ("d-sharpsharp", 1, 4),
    ("df", 1, -2),
    ("dff", 1, -4),
    ("dqf", 1, -1),
    ("dqs", 1, 1),
    ("ds", 1, 2),
    ("dss", 1, 4),
    ("dtqf", 1, -3),
    ("dtqs", 1, 3),
    ("dx", 1, 4),
    ("e", 2, 0),
    ("e-flat", 2, -2),
    ("e-flatflat", 2, -4),
    ("e-natural", 2, 0),
    ("e-sharp", 2, 2),
    ("e-sharpsharp", 2, 4),
    ("ef", 2, -2),
    ("eff", 2, -4),
    ("eqf", 2, -1),
    ("eqs", 2, 1),
    ("es", 2, 2),
    ("ess", 2, 4),
    ("etqf", 2, -3),
    ("etqs", 2, 3),
    ("ex", 2, 4),
    ("f", 3, 0),
    ("f-flat", 3, -2),
    ("f-flatflat", 3, -4),
    ("f-natural", 3, 0),
    ("f-sharp", 3, 2),
    ("f-sharpsharp", 3, 4),
    ("ff", 3, -2),
    ("fff", 3, -4),
    ("fqf", 3, -1),
    ("fqs", 3, 1),
    ("fs", 3, 2),
    ("fss", 3, 4),
    ("ftqf", 3, -3),
    ("ftqs", 3, 3),
    ("fx", 3, 4),
    ("g", 4, 0),
    ("g-flat", 4, -2),
    ("g-flatflat", 4, -4),
    ("g-natural", 4, 0),
    ("g-sharp", 4, 2),
    ("g-sharpsharp", 4, 4),
    ("gf", 4, -2),
    ("gff", 4, -4),
    ("gqf", 4, -1),
    ("gqs", 4, 1),
    ("gs", 4, 2),
    ("gss", 4, 4),
    ("gtqf", 4, -3),
    ("gtqs", 4, 3),
    ("gx", 4, 4),
];

#[rustfmt::skip]
static ESPANOL_NAMES: &[(&str, u8, i8)] = &[
    ("do", 0, 0),
    ("dob", 0, -2),
    ("dobb", 0, -4),
    ("docb", 0, -1),
    ("docs", 0, 1),
    ("dos", 0, 2),
    ("doss", 0, 4),
    ("dotcb", 0, -3),
    ("dotcs", 0, 3),
    ("dox", 0, 4),
    ("fa", 3, 0),
    ("fab", 3, -2),
    ("fabb", 3, -4),
    ("facb", 3, -1),
    ("facs", 3, 1),
    ("fas", 3, 2),
    ("fass", 3, 4),
    ("fatcb", 3, -3),
    ("fatcs", 3, 3),
    ("fax", 3, 4),
    ("la", 5, 0),
    ("lab", 5, -2),
    ("labb", 5, -4),
    ("lacb", 5, -1),
    ("lacs", 5, 1),
    ("las", 5, 2),
    ("lass", 5, 4),
    ("latcb", 5, -3),
    ("latcs", 5, 3),
    ("lax", 5, 4),
    ("mi", 2, 0),
    ("mib", 2, -2),
    ("mibb", 2, -4),
    ("micb", 2, -1),
    ("mics", 2, 1),
    ("mis", 2, 2),
    ("miss", 2, 4),
    ("mitcb", 2, -3),
    ("mitcs", 2, 3),
    ("mix", 2, 4),
    ("re", 1, 0),
    ("reb", 1, -2),
    ("rebb", 1, -4),
    ("recb", 1, -1),
    ("recs", 1, 1),
    ("res", 1, 2),
    ("ress", 1, 4),
    ("retcb", 1, -3),
    ("retcs", 1, 3),
    ("rex", 1, 4),
    ("si", 6, 0),
    ("sib", 6, -2),
    ("sibb", 6, -4),
    ("sicb", 6, -1),
    ("sics", 6, 1),
    ("sis", 6, 2),
    ("siss", 6, 4),
    ("sitcb", 6, -3),
    ("sitcs", 6, 3),
    ("six", 6, 4),
    ("sol", 4, 0),
    ("solb", 4, -2),
    ("solbb", 4, -4),
    ("solcb", 4, -1),
    ("solcs", 4, 1),
    ("sols", 4, 2),
    ("solss", 4, 4),
    ("soltcb", 4, -3),
    ("soltcs", 4, 3),
    ("solx", 4, 4),
];

#[rustfmt::skip]
static FRANCAIS_NAMES: &[(&str, u8, i8)] = &[
    ("do", 0, 0),
    ("dob", 0, -2),
    ("dobb", 0, -4),
    ("dobsb", 0, -3),
    ("dod", 0, 2),
    ("dodd", 0, 4),
    ("dodsd", 0, 3),
    ("dosb", 0, -1),
    ("dosd", 0, 1),
    ("dox", 0, 4),
    ("fa", 3, 0),
    ("fab", 3, -2),
    ("fabb", 3, -4),
    ("fabsb", 3, -3),
    ("fad", 3, 2),
    ("fadd", 3, 4),
    ("fadsd", 3, 3),
    ("fasb", 3, -1),
    ("fasd", 3, 1),
    ("fax", 3, 4),
    ("la", 5, 0),
    ("lab", 5, -2),
    ("labb", 5, -4),
    ("labsb", 5, -3),
    ("lad", 5, 2),
    ("ladd", 5, 4),
    ("ladsd", 5, 3),
    ("lasb", 5, -1),
    ("lasd", 5, 1),
    ("lax", 5, 4),
    ("mi", 2, 0),
    ("mib", 2, -2),
    ("mibb", 2, -4),
    ("mibsb", 2, -3),
    ("mid", 2, 2),
    ("midd", 2, 4),
    ("midsd", 2, 3),
    ("misb", 2, -1),
    ("misd", 2, 1),
    ("mix", 2, 4),
    ("re", 1, 0),
    ("reb", 1, -2),
    ("rebb", 1, -4),
    ("rebsb", 1, -3),
    ("red", 1, 2),
    ("redd", 1, 4),
    ("redsd", 1, 3),
    ("resb", 1, -1),
    ("resd", 1, 1),
    ("rex", 1, 4),
    ("ré", 1, 0),
    ("réb", 1, -2),
    ("rébb", 1, -4),
    ("rébsb", 1, -3),
    ("réd", 1, 2),
    ("rédd", 1, 4),
    ("rédsd", 1, 3),
    ("résb", 1, -1),
    ("résd", 1, 1),
    ("réx", 1, 4),
    ("si", 6, 0),
    ("sib", 6, -2),
    ("sibb", 6, -4),
    ("sibsb", 6, -3),
    ("sid", 6, 2),
    ("sidd", 6, 4),
    ("sidsd", 6, 3),
    ("sisb", 6, -1),
    ("sisd", 6, 1),
    ("six", 6, 4),
    ("sol", 4, 0),
    ("solb", 4, -2),
    ("solbb", 4, -4),
    ("solbsb", 4, -3),
    ("sold", 4, 2),
    ("soldd", 4, 4),
    ("soldsd", 4, 3),
    ("solsb", 4, -1),
    ("solsd", 4, 1),
    ("solx", 4, 4),
];

#[rustfmt::skip]
static ITALIANO_NAMES: &[(&str, u8, i8)] = &[
    ("do", 0, 0),
    ("dob", 0, -2),
    ("dobb", 0, -4),
    ("dobsb", 0, -3),
    ("dod", 0, 2),
    ("dodd", 0, 4),
    ("dodsd", 0, 3),
    ("dosb", 0, -1),
    ("dosd", 0, 1),
    ("fa", 3, 0),
    ("fab", 3, -2),
    ("fabb", 3, -4),
    ("fabsb", 3, -3),
    ("fad", 3, 2),
    ("fadd", 3, 4),
    ("fadsd", 3, 3),
    ("fasb", 3, -1),
    ("fasd", 3, 1),
    ("la", 5, 0),
    ("lab", 5, -2),
    ("labb", 5, -4),
    ("labsb", 5, -3),
    ("lad", 5, 2),
    ("ladd", 5, 4),
    ("ladsd", 5, 3),
    ("lasb", 5, -1),
    ("lasd", 5, 1),
    ("mi", 2, 0),
    ("mib", 2, -2),
    ("mibb", 2, -4),
    ("mibsb", 2, -3),
    ("mid", 2, 2),
    ("midd", 2, 4),
    ("midsd", 2, 3),
    ("misb", 2, -1),
    ("misd", 2, 1),
    ("re", 1, 0),
    ("reb", 1, -2),
    ("rebb", 1, -4),
    ("rebsb", 1, -3),
    ("red", 1, 2),
    ("redd", 1, 4),
    ("redsd", 1, 3),
    ("resb", 1, -1),
    ("resd", 1, 1),
    ("si", 6, 0),
    ("sib", 6, -2),
    ("sibb", 6, -4),
    ("sibsb", 6, -3),
    ("sid", 6, 2),
    ("sidd", 6, 4),
    ("sidsd", 6, 3),
    ("sisb", 6, -1),
    ("sisd", 6, 1),
    ("sol", 4, 0),
    ("solb", 4, -2),
    ("solbb", 4, -4),
    ("solbsb", 4, -3),
    ("sold", 4, 2),
    ("soldd", 4, 4),
    ("soldsd", 4, 3),
    ("solsb", 4, -1),
    ("solsd", 4, 1),
];

#[rustfmt::skip]
static NEDERLANDS_NAMES: &[(&str, u8, i8)] = &[
    ("a", 5, 0),
    ("aeh", 5, -1),
    ("aes", 5, -2),
    ("aeseh", 5, -3),
    ("aeses", 5, -4),
    ("aih", 5, 1),
    ("ais", 5, 2),
    ("aisih", 5, 3),
    ("aisis", 5, 4),
    ("as", 5, -2),
    ("ases", 5, -4),
    ("b", 6, 0),
    ("beh", 6, -1),
    ("bes", 6, -2),
    ("beseh", 6, -3),
    ("beses", 6, -4),
    ("bih", 6, 1),
    ("bis", 6, 2),
    ("bisih", 6, 3),
    ("bisis", 6, 4),
    ("c", 0, 0),
    ("ceh", 0, -1),
    ("ces", 0, -2),
    ("ceseh", 0, -3),
    ("ceses", 0, -4),
    ("cih", 0, 1),
    ("cis", 0, 2),
    ("cisih", 0, 3),
    ("cisis", 0, 4),
    ("d", 1, 0),
    ("deh", 1, -1),
    ("des", 1, -2),
    ("deseh", 1, -3),
    ("deses", 1, -4),
    ("dih", 1, 1),
    ("dis", 1, 2),
    ("disih", 1, 3),
    ("disis", 1, 4),
    ("e", 2, 0),
    ("eeh", 2, -1),
    ("ees", 2, -2),
    ("eeseh", 2, -3),
    ("eeses", 2, -4),
    ("eih", 2, 1),
    ("eis", 2, 2),
    ("eisih", 2, 3),
    ("eisis", 2, 4),
    ("es", 2, -2),
    ("eses", 2, -4),
    ("f", 3, 0),
    ("feh", 3, -1),
    ("fes", 3, -2),
    ("feseh", 3, -3),
    ("feses", 3, -4),
    ("fih", 3, 1),
    ("fis", 3, 2),
    ("fisih", 3, 3),
    ("fisis", 3, 4),
    ("g", 4, 0),
    ("geh", 4, -1),
    ("ges", 4, -2),
    ("geseh", 4, -3),
    ("geses", 4, -4),
    ("gih", 4, 1),
    ("gis", 4, 2),
    ("gisih", 4, 3),
    ("gisis", 4, 4),
];

#[rustfmt::skip]
static NORSK_NAMES: &[(&str, u8, i8)] = &[
    ("a", 5, 0),
    ("aeh", 5, -1),
    ("aes", 5, -2),
    ("aeseh", 5, -3),
    ("aeses", 5, -4),
    ("aess", 5, -2),
    ("aesseh", 5, -3),
    ("aessess", 5, -4),
    ("aih", 5, 1),
    ("ais", 5, 2),
    ("aisih", 5, 3),
    ("aisis", 5, 4),
    ("aiss", 5, 2),
    ("aissih", 5, 3),
    ("aississ", 5, 4),
    ("as", 5, -2),
    ("ases", 5, -4),
    ("ass", 5, -2),
    ("assess", 5, -4),
    ("b", 6, -2),
    ("beh", 6, -3),
    ("bes", 6, -4),
    ("bess", 6, -4),
    ("c", 0, 0),
    ("ceh", 0, -1),
    ("ces", 0, -2),
    ("ceseh", 0, -3),
    ("ceses", 0, -4),
    ("cess", 0, -2),
    ("cesseh", 0, -3),
    ("cessess", 0, -4),
    ("cih", 0, 1),
    ("cis", 0, 2),
    ("cisih", 0, 3),
    ("cisis", 0, 4),
    ("ciss", 0, 2),
    ("cissih", 0, 3),
    ("cississ", 0, 4),
    ("d", 1, 0),
    ("deh", 1, -1),
    ("des", 1, -2),
    ("deseh", 1, -3),
    ("deses", 1, -4),
    ("dess", 1, -2),
    ("desseh", 1, -3),
    ("dessess", 1, -4),
    ("dih", 1, 1),
    ("dis", 1, 2),
    ("disih", 1, 3),
    ("disis", 1, 4),
    ("diss", 1, 2),
    ("dissih", 1, 3),
    ("dississ", 1, 4),
    ("e", 2, 0),
    ("eeh", 2, -1),
    ("ees", 2, -2),
    ("eeseh", 2, -3),
    ("eeses", 2, -4),
    ("eess", 2, -2),
    ("eesseh", 2, -3),
    ("eessess", 2, -4),
    ("eih", 2, 1),
    ("eis", 2, 2),
    ("eisih", 2, 3),
    ("eisis", 2, 4),
    ("eiss", 2, 2),
    ("eissih", 2, 3),
    ("eississ", 2, 4),
    ("es", 2, -2),
    ("eses", 2, -4),
    ("ess", 2, -2),
    ("essess", 2, -4),
    ("f", 3, 0),
    ("feh", 3, -1),
    ("fes", 3, -2),
    ("feseh", 3, -3),
    ("feses", 3, -4),
    ("fess", 3, -2),
    ("fesseh", 3, -3),
    ("fessess", 3, -4),
    ("fih", 3, 1),
    ("fis", 3, 2),
    ("fisih", 3, 3),
    ("fisis", 3, 4),
    ("fiss", 3, 2),
    ("fissih", 3, 3),
    ("fississ", 3, 4),
    ("g", 4, 0),
    ("geh", 4, -1),
    ("ges", 4, -2),
    ("geseh", 4, -3),
    ("geses", 4, -4),
    ("gess", 4, -2),
    ("gesseh", 4, -3),
    ("gessess", 4, -4),
    ("gih", 4, 1),
    ("gis", 4, 2),
    ("gisih", 4, 3),
    ("gisis", 4, 4),
    ("giss", 4, 2),
    ("gissih", 4, 3),
    ("gississ", 4, 4),
    ("h", 6, 0),
    ("heh", 6, -1),
    ("hih", 6, 1),
    ("his", 6, 2),
    ("hisih", 6, 3),
    ("hisis", 6, 4),
    ("hiss", 6, 2),
    ("hissih", 6, 3),
    ("hississ", 6, 4),
];

#[rustfmt::skip]
static PORTUGUES_NAMES: &[(&str, u8, i8)] = &[
    ("do", 0, 0),
    ("dob", 0, -2),
    ("dobb", 0, -4),
    ("dobqt", 0, -1),
    ("dobtqt", 0, -3),
    ("dos", 0, 2),
    ("dosqt", 0, 1),
    ("doss", 0, 4),
    ("dostqt", 0, 3),
    ("fa", 3, 0),
    ("fab", 3, -2),
    ("fabb", 3, -4),
    ("fabqt", 3, -1),
    ("fabtqt", 3, -3),
    ("fas", 3, 2),
    ("fasqt", 3, 1),
    ("fass", 3, 4),
    ("fastqt", 3, 3),
    ("la", 5, 0),
    ("lab", 5, -2),
    ("labb", 5, -4),
    ("labqt", 5, -1),
    ("labtqt", 5, -3),
    ("las", 5, 2),
    ("lasqt", 5, 1),
    ("lass", 5, 4),
    ("lastqt", 5, 3),
    ("mi", 2, 0),
    ("mib", 2, -2),
    ("mibb", 2, -4),
    ("mibqt", 2, -1),
    ("mibtqt", 2, -3),
    ("mis", 2, 2),
    ("misqt", 2, 1),
    ("miss", 2, 4),
    ("mistqt", 2, 3),
    ("re", 1, 0),
    ("reb", 1, -2),
    ("rebb", 1, -4),
    ("rebqt", 1, -1),
    ("rebtqt", 1, -3),
    ("res", 1, 2),
    ("resqt", 1, 1),
    ("ress", 1, 4),
    ("restqt", 1, 3),
    ("si", 6, 0),
    ("sib", 6, -2),
    ("sibb", 6, -4),
    ("sibqt", 6, -1),
    ("sibtqt", 6, -3),
    ("sis", 6, 2),
    ("sisqt", 6, 1),
    ("siss", 6, 4),
    ("sistqt", 6, 3),
    ("sol", 4, 0),
    ("solb", 4, -2),
    ("solbb", 4, -4),
    ("solbqt", 4, -1),
    ("solbtqt", 4, -3),
    ("sols", 4, 2),
    ("solsqt", 4, 1),
    ("solss", 4, 4),
    ("solstqt", 4, 3),
];

#[rustfmt::skip]
static SEMI_GERMAN_NAMES: &[(&str, u8, i8)] = &[
    ("a", 5, 0),
    ("aeh", 5, -1),
    ("ah", 5, -1),
    ("aih", 5, 1),
    ("ais", 5, 2),
    ("aisih", 5, 3),
    ("aisis", 5, 4),
    ("as", 5, -2),
    ("asah", 5, -3),
    ("asas", 5, -4),
    ("aseh", 5, -3),
    ("ases", 5, -4),
    ("b", 6, -2),
    ("c", 0, 0),
    ("ceh", 0, -1),
    ("ces", 0, -2),
    ("ceseh", 0, -3),
    ("ceses", 0, -4),
    ("cih", 0, 1),
    ("cis", 0, 2),
    ("cisih", 0, 3),
    ("cisis", 0, 4),
    ("d", 1, 0),
    ("deh", 1, -1),
    ("des", 1, -2),
    ("deseh", 1, -3),
    ("deses", 1, -4),
    ("dih", 1, 1),
    ("dis", 1, 2),
    ("disih", 1, 3),
    ("disis", 1, 4),
    ("e", 2, 0),
    ("eeh", 2, -1),
    ("eh", 2, -1),
    ("eih", 2, 1),
    ("eis", 2, 2),
    ("eisih", 2, 3),
    ("eisis", 2, 4),
    ("es", 2, -2),
    ("eseh", 2, -3),
    ("eses", 2, -4),
    ("f", 3, 0),
    ("feh", 3, -1),
    ("fes", 3, -2),
    ("feseh", 3, -3),
    ("feses", 3, -4),
    ("fih", 3, 1),
    ("fis", 3, 2),
    ("fisih", 3, 3),
    ("fisis", 3, 4),
    ("g", 4, 0),
    ("geh", 4, -1),
    ("ges", 4, -2),
    ("geseh", 4, -3),
    ("geses", 4, -4),
    ("gih", 4, 1),
    ("gis", 4, 2),
    ("gisih", 4, 3),
    ("gisis", 4, 4),
    ("h", 6, 0),
    ("heh", 6, -1),
    ("heseh", 6, -3),
    ("heses", 6, -4),
    ("hih", 6, 1),
    ("his", 6, 2),
    ("hisih", 6, 3),
    ("hisis", 6, 4),
];

#[rustfmt::skip]
static SUOMI_NAMES: &[(&str, u8, i8)] = &[
    ("a", 5, 0),
    ("aeh", 5, -1),
    ("aih", 5, 1),
    ("ais", 5, 2),
    ("aisih", 5, 3),
    ("aisis", 5, 4),
    ("as", 5, -2),
    ("asah", 5, -3),
    ("asas", 5, -4),
    ("aseh", 5, -3),
    ("ases", 5, -4),
    ("b", 6, -2),
    ("bb", 6, -4),
    ("bes", 6, -4),
    ("c", 0, 0),
    ("ceh", 0, -1),
    ("ces", 0, -2),
    ("ceseh", 0, -3),
    ("ceses", 0, -4),
    ("cih", 0, 1),
    ("cis", 0, 2),
    ("cisih", 0, 3),
    ("cisis", 0, 4),
    ("d", 1, 0),
    ("deh", 1, -1),
    ("des", 1, -2),
    ("deseh", 1, -3),
    ("deses", 1, -4),
    ("dih", 1, 1),
    ("dis", 1, 2),
    ("disih", 1, 3),
    ("disis", 1, 4),
    ("e", 2, 0),
    ("eeh", 2, -1),
    ("eih", 2, 1),
    ("eis", 2, 2),
    ("eisih", 2, 3),
    ("eisis", 2, 4),
    ("es", 2, -2),
    ("eseh", 2, -3),
    ("eses", 2, -4),
    ("f", 3, 0),
    ("feh", 3, -1),
    ("fes", 3, -2),
    ("feseh", 3, -3),
    ("feses", 3, -4),
    ("fih", 3, 1),
    ("fis", 3, 2),
    ("fisih", 3, 3),
    ("fisis", 3, 4),
    ("g", 4, 0),
    ("geh", 4, -1),
    ("ges", 4, -2),
    ("geseh", 4, -3),
    ("geses", 4, -4),
    ("gih", 4, 1),
    ("gis", 4, 2),
    ("gisih", 4, 3),
    ("gisis", 4, 4),
    ("h", 6, 0),
    ("heh", 6, -1),
    ("heseh", 6, -3),
    ("heses", 6, -4),
    ("hih", 6, 1),
    ("his", 6, 2),
    ("hisih", 6, 3),
    ("hisis", 6, 4),
];

#[rustfmt::skip]
static SVENSKA_NAMES: &[(&str, u8, i8)] = &[
    ("a", 5, 0),
    ("aeh", 5, -1),
    ("aih", 5, 1),
    ("aiss", 5, 2),
    ("aissih", 5, 3),
    ("aississ", 5, 4),
    ("ass", 5, -2),
    ("asseh", 5, -3),
    ("assess", 5, -4),
    ("b", 6, -2),
    ("c", 0, 0),
    ("ceh", 0, -1),
    ("cess", 0, -2),
    ("cesseh", 0, -3),
    ("cessess", 0, -4),
    ("cih", 0, 1),
    ("ciss", 0, 2),
    ("cissih", 0, 3),
    ("cississ", 0, 4),
    ("d", 1, 0),
    ("deh", 1, -1),
    ("dess", 1, -2),
    ("desseh", 1, -3),
    ("dessess", 1, -4),
    ("dih", 1, 1),
    ("diss", 1, 2),
    ("dissih", 1, 3),
    ("dississ", 1, 4),
    ("e", 2, 0),
    ("eeh", 2, -1),
    ("eih", 2, 1),
    ("eiss", 2, 2),
    ("eissih", 2, 3),
    ("eississ", 2, 4),
    ("ess", 2, -2),
    ("esseh", 2, -3),
    ("essess", 2, -4),
    ("f", 3, 0),
    ("feh", 3, -1),
    ("fess", 3, -2),
    ("fesseh", 3, -3),
    ("fessess", 3, -4),
    ("fih", 3, 1),
    ("fiss", 3, 2),
    ("fissih", 3, 3),
    ("fississ", 3, 4),
    ("g", 4, 0),
    ("geh", 4, -1),
    ("gess", 4, -2),
    ("gesseh", 4, -3),
    ("gessess", 4, -4),
    ("gih", 4, 1),
    ("giss", 4, 2),
    ("gissih", 4, 3),
    ("gississ", 4, 4),
    ("h", 6, 0),
    ("heh", 6, -1),
    ("hesseh", 6, -3),
    ("hessess", 6, -4),
    ("hih", 6, 1),
    ("hiss", 6, 2),
    ("hissih", 6, 3),
    ("hississ", 6, 4),
];

#[rustfmt::skip]
static VLAAMS_NAMES: &[(&str, u8, i8)] = &[
    ("do", 0, 0),
    ("dob", 0, -2),
    ("dobb", 0, -4),
    ("dobhb", 0, -3),
    ("dohb", 0, -1),
    ("dohk", 0, 1),
    ("dok", 0, 2),
    ("dokhk", 0, 3),
    ("dokk", 0, 4),
    ("fa", 3, 0),
    ("fab", 3, -2),
    ("fabb", 3, -4),
    ("fabhb", 3, -3),
    ("fahb", 3, -1),
    ("fahk", 3, 1),
    ("fak", 3, 2),
    ("fakhk", 3, 3),
    ("fakk", 3, 4),
    ("la", 5, 0),
    ("lab", 5, -2),
    ("labb", 5, -4),
    ("labhb", 5, -3),
    ("lahb", 5, -1),
    ("lahk", 5, 1),
    ("lak", 5, 2),
    ("lakhk", 5, 3),
    ("lakk", 5, 4),
    ("mi", 2, 0),
    ("mib", 2, -2),
    ("mibb", 2, -4),
    ("mibhb", 2, -3),
    ("mihb", 2, -1),
    ("mihk", 2, 1),
    ("mik", 2, 2),
    ("mikhk", 2, 3),
    ("mikk", 2, 4),
    ("re", 1, 0),
    ("reb", 1, -2),
    ("rebb", 1, -4),
    ("rebhb", 1, -3),
    ("rehb", 1, -1),
    ("rehk", 1, 1),
    ("rek", 1, 2),
    ("rekhk", 1, 3),
    ("rekk", 1, 4),
    ("si", 6, 0),
    ("sib", 6, -2),
    ("sibb", 6, -4),
    ("sibhb", 6, -3),
    ("sihb", 6, -1),
    ("sihk", 6, 1),
    ("sik", 6, 2),
    ("sikhk", 6, 3),
    ("sikk", 6, 4),
    ("sol", 4, 0),
    ("solb", 4, -2),
    ("solbb", 4, -4),
    ("solbhb", 4, -3),
    ("solhb", 4, -1),
    ("solhk", 4, 1),
    ("solk", 4, 2),
    ("solkhk", 4, 3),
    ("solkk", 4, 4),
];

#[cfg(test)]
mod tests {
    use super::Language;
    use proptest::prelude::*;

    #[test]
    fn spell_prefers_the_short_form_over_a_spelled_out_alias() {
        // English lists both `ef` and `e-flat` for e-flat; the terse one wins.
        // Kept as a literal pin of this specific spelling alongside the
        // general shortest-spelling property below.
        assert_eq!(Language::English.spell(2, -2), Some("ef"));
        assert_eq!(Language::English.spell(0, 2), Some("cs"));
        // A natural keeps its bare letter, not `e-natural`.
        assert_eq!(Language::English.spell(2, 0), Some("e"));
    }

    #[test]
    fn spell_returns_none_for_a_pitch_no_spelling_covers() {
        // No language names a pitch this sharp (alteration 6); the tables stop at
        // the double sharp, +4.
        assert_eq!(Language::English.spell(0, 6), None);
    }

    /// Every `Language` variant, for sampling and for exhaustive iteration.
    const ALL_LANGUAGES: [Language; 13] = [
        Language::Catalan,
        Language::Deutsch,
        Language::English,
        Language::Espanol,
        Language::Francais,
        Language::Italiano,
        Language::Nederlands,
        Language::Norsk,
        Language::Portugues,
        Language::SemiGerman,
        Language::Suomi,
        Language::Svenska,
        Language::Vlaams,
    ];

    fn language_strategy() -> impl Strategy<Value = Language> {
        proptest::sample::select(&ALL_LANGUAGES[..])
    }

    proptest! {
        /// Spelling a pitch and reading the spelling back must return the
        /// pitch you started with — otherwise a refactoring that writes a
        /// spelled note wouldn't be able to trust its own output.
        #[test]
        fn spell_and_note_round_trip(
            language in language_strategy(),
            note_name in 0u8..7,
            alteration in -4i8..=4,
        ) {
            let Some(spelling) = language.spell(note_name, alteration) else {
                // Not every language names every pitch; nothing to round-trip.
                return Ok(());
            };
            prop_assert_eq!(language.note(spelling), Some((note_name, alteration)));
        }

        /// `spell` documents itself as choosing the shortest of several
        /// spellings for the same pitch (English `ef` over `e-flat`); check
        /// that against every other table entry sharing that pitch, not just
        /// the one example the pinned test above covers.
        #[test]
        fn spell_returns_the_shortest_entry_for_the_pitch(
            language in language_strategy(),
            note_name in 0u8..7,
            alteration in -4i8..=4,
        ) {
            let Some(spelling) = language.spell(note_name, alteration) else {
                return Ok(());
            };
            for &(name, note, alt) in language.table() {
                if note == note_name && alt == alteration {
                    prop_assert!(spelling.len() <= name.len());
                }
            }
        }
    }

    #[test]
    fn note_agrees_with_every_table_entry() {
        // Exhaustive rather than random: each language's table is small and
        // fully enumerable, so checking every entry is strictly stronger
        // than sampling and just as cheap.
        for &language in &ALL_LANGUAGES {
            for &(name, note, alt) in language.table() {
                assert_eq!(
                    language.note(name),
                    Some((note, alt)),
                    "{language:?} table entry {name:?} did not round-trip through note()"
                );
            }
        }
    }
}
